### ISSUE TITLE
make urls clickable (or is that touchable?)

### ISSUE THREAD

**Issue by mhellwig** [konradrenner/kolabnotes-android#112]
A lot of times, a note will include a http(s) link to some website. currently, there is no way to go to this website from inside kolabnotes. Or if there is, I'm too stupid to do it. Tapping on the link does nothing.

**Comment by konradrenner** [comment]
Yeah good point, this would definitively be an enhancement

**Comment by konradrenner** [comment]
With the next release it is possible to "click" on links in the stock Android editor (is used when Richeditor is disabled in the general settings). For the Richeditor I have created an issue for the devs of the editor: https://github.com/wasabeef/richeditor-android/issues/49

**Comment by AkashAndi** [comment]
is it done?

**Comment by konradrenner** [comment]
If you don't use the Richtext Editor, it is possible. But if you use the richtext editor, it depends on the mentioned issue of the richeditor-android project which seems to still be open.

**Comment by AkashAndi** [comment]
How can I make content renders same as rich editor without using rich editor ?

**Comment by konradrenner** [comment]
This is not possible, because the standard editor lacks many features of the Richeditor.  So there are 2 possible solutions for this problem:
1. You wait that anybody fixes it in the richeditor-android project (which is not related with this project)
2. You fix it und create a pull request in the richeditor-android project
