### ISSUE TITLE
Usability improvement: Selection of account when quick-adding notes

### ISSUE THREAD

**Issue by greve** [konradrenner/kolabnotes-android#124]
Thank you all so much for your work on Kolab Notes! All of you rock big time! (it cannot be said often enough)

Here is a feature request / usability enhancement:

When quick adding notes, Kolab Notes currently first opens a small window for account selection, and then opens a new note for that account. That's one more interaction than needed in 90% of the cases, since often you will be in work or private mode (in my case) and then the notes should all go to the same account.

Usability wise it would be much better if for a new note, it would select a sane default (the notebook/account you are in when the application is running, the last notebook/account you wrote to for quick adding notes) and then in the note edit dialogue, allow to change the account by making the account name shown on top a selector for the account (and ideally also notebook).

That would

 (a) eliminate the need for the additional interaction, and that selection box can then go entirely;
 (b) offer the most logical and user friendly (IMHO) way to move notes between note books and accounts when editing them.

**Comment by konradrenner** [comment]
@greve  Thank you!
Point (b) is a really strong argument for this issue. I don't know how often notes are moved from one account to another, but it would be a cool feature indeed.

Implementation should be not too difficult:
If the account is changed in the DetailActivity and the note already exists in the former account, it must be deleted there and a new one must be created in the selected account, if the save button is selected. If the note doesn't exist, it just must be created in the selected account.

The important thing is, that after account change, the ActiveAccountRepository.switchAccount, Utils.getSelectedTagName and Utils.setSelectedNotebookName methods must be called, so that the state of selected accounts/notebooks is correct.

**Comment by konradrenner** [comment]
Description of the steps todo:
- create a menu option for switching account of note (one can use the existing dialog for account changing)
- remove the appearence of the dialog after the detail acitivty is launched from the share menu
- selected notebook should be the alphabetically fist in of the selected account, or extend the account switching dialog, so that a user can select the notebook of the new account already at time of account changing
- do the steps described in the previous comment

@greve : an open question for me is how tags should be handled? If a note has tags which doesn't exist in the new account, how should it be handled?
a) The note will loose all tags (because it is a new account, maybe the context is different and so the tags are different)
b) Search in the account for tags with the same name, if the tag is not found, the note will loose the tag
c) Search in the account for tags with the same name, if the tag is not found a new one will be created

Another question for b) and c) : What if tags in the other account are configured other then in the previous account (other colour, priority)? Just use the tag and change nothing of the tag configuration or change the tag configuration?

**Comment by greve** [comment]
(a) may be defensible, but is probably not what the user intended. And it is likely easier to remove that tag later, rather than re-adding it. 

So (c) would seem ideal. 

And moving a note should absolutely NEVER change the tag configuration of an existing account. 

So I would say from a usability perspective it should use the corresponding tag (if one exists, as it exists) and create the new tag with the same configuration as it was on the account from which the note came.

But that may be a second mile stone in my opinion. For a first mile stone (a) would likely be much more easily achieved (pure speculation on my side) and so it could be chosen until (c) can be done well.

Would that work for you?

**Comment by konradrenner** [comment]
Thanks for the reply! Because the sync is decoupled of the app logic, I don't think it is a really hard task to do c) .  
It will just be 2-3 additional calls of already defined database operations (important: every time a note is deleted, what will technically be done in the old account if a note is migrated from 1 account to another, the Note - Tag assignment in the old account must also be deleted via NoteTagRepository.delete(accountInformations, noteUID)).

The sync logic automatically checks, what was done since last sync and will create/delete new tags or assignments.

**Comment by konradrenner** [comment]
So with the new app shortcut functionality this issue has now a top priority. Will do this next.

**Comment by konradrenner** [comment]
start point: ChooseAccountDialogFragment.java

**Comment by konradrenner** [comment]
remove call from DetailActivity and create call in DetailFragment (new Menu Item). MainActivity must also implement the OnAccountChooseListener interface for handling the account change (DetailActivity already does it, but must be extended liked described in the comments here).

Possible icon: https://material.io/icons/#ic_assignment_ind

**Comment by konradrenner** [comment]
I have reflected on the "move" of the note. I don't think it is a good idea to delete the note from the "old" account. It is problematic in many ways. So the account switch will just create a note, not remove from a previous selected account and it will just create the note after hitting the "ok" button.

One other thing: if the app is in tablet mode, the MainActivity listener must reload the overview data after account change.

**Comment by konradrenner** [comment]
implemented with version 2.7.2
