### ISSUE TITLE
no Sync with server IMAP Server 

### ISSUE THREAD

**Issue by Manuelibt** [konradrenner/kolabnotes-android#142]
Is any special configuration in ther Server needed? I get the message Connection dropped by Server. Is it a known issue? Thanks.

**Comment by Manuelibt** [comment]
Here is the whole message: Java.lang.illegalstateException: korrex.mail.MessagingExecption: recvform failed: EDTIMEDOUT (Connection Timed Out) Nestes exception is: Java.net.SocketException : recvform failed: ETIMEDOUT (Connection time out). Maybe it helps to solve it...

**Comment by Manuelibt** [comment]
And another errormessage: 
Java.lang.illegalstateException: korrex.mail.MessagingExecption: Connection dropped by server? Nested exception is: Java.io.IOException: Connection dropped by server? 
Sorry for spamming...

**Comment by konradrenner** [comment]
Hi, thanks for the informations! Can you sync your Mails from this server with a Mail app? Can you send me a screenshot or Infos of the account settings?

**Comment by konradrenner** [comment]
I don't need your Mail address but the extended options of the settings are interesting and the IMAP Server URL is also important for me, so that I can help you.

**Comment by Manuelibt** [comment]
Hi Konrad,
thanks for your answere. Here is a screenshot of my settings. 
Yes it is possible to sync with other mail apps. I'm using the standard app in cyanogenmod 13.  If you need ans further serverdetails i would rather send you a pm. Is this possible in github. Sorry i'm such a noob..
![tmp_2888-img_20161101_183936-801183061](https://cloud.githubusercontent.com/assets/20125642/19900201/fa1a56fe-a062-11e6-916d-132374e9aa61.jpg)

**Comment by Manuelibt** [comment]
To unmark the "geteilte notizbücher" makes no difference, regarding the issue.

**Comment by konradrenner** [comment]
Do you have a folder "Notes" on your mail Server?

**Comment by Manuelibt** [comment]
Yes. I created it after the first error message.

**Comment by konradrenner** [comment]
Are you the admin on this server? Is it possible for you that you create a test account for me?

Can you try if the sync works if you specify "143" for the port?

**Comment by Manuelibt** [comment]
With 143 for the port the programm is not finding the Notes folder. 

Sync failed
"java.lang.illegalStateException:korex.mail.FolderNotFoundException: Notes not found"

But the folder is there...

I created a testaccount for you. How can i send you the login data?

**Comment by konradrenner** [comment]
can you send me a screenshot of your folder hierarchy? my mail address is: koni.renner@gmail.com

**Comment by konradrenner** [comment]
can you send me a screenshot of your folder hierarchy? my mail address is: koni.renner@gmail.com

**Comment by konradrenner** [comment]
can you send me a screenshot of your folder hierarchy? my mail address is: koni.renner@gmail.com

**Comment by konradrenner** [comment]
with version 2.3.2 this problem should be fixed. description of the problem: I don't know why but the described server stores the top level folders with the prefix "INBOX.".  I have pushed a fix so that the configuration folder also gets this prefix.

During account creation the root folder must also be specified by the user with the prefix "INBOX.", so in the case of this issue the root folder value must be specified with the value "INBOX.Notes".

**Comment by kael** [comment]
I'm facing a similar issue with version 4.0.0.

Synchronization seems to fail because it can't find the Notes mailbox, using Kolab or normal notes. I've tested with `Notes` & `INBOX.Notes` but it doesn't seem to work.

Could you please add a description of the prerequisites on IMAP side ? How the `Notes` (and the `Configuration`) mailbox should be created, considering for example the returned namespace of the Fastmail server is `/` ?

Also, are there any IMAP METADATA to add to the mailbox, something similar to [this](https://git.kolab.org/T1108) ?

**Comment by konradrenner** [comment]
Hi,
first of all, if you are using a "plain IMAP" server, you must disable the "Kolab extensions" and "Shared notebooks" option when creating an account.
Depending on your IMAP Server, the Notes folder must be in the root directory or under INBOX (e.g. INBOX/Notes ).

Metadata is automatically checked, if you are enabling the Kolab extensions. So if you are not using a Kolab server, you don't have to add any Metadata.

Please let me know if the information was helpful.

Yours,
Konrad
