### ISSUE TITLE
Can't share notes on whattsap

### ISSUE THREAD

**Issue by Saahir1** [konradrenner/kolabnotes-android#168]
#### Expected behavior
After writing notes we should be able to share them on different social networking platforms like Facebook, whattsap, Instagram etc. 

#### Actual behavior
After Saving the created notes I tried to share the information with my beastie on whattsap but I was not able to perform the operation as the message sending option is not responding. 

#### How to reproduce
- Firstly open kolab notes and write a note of your interest and save it. 
- After saving the notes click on the icon right at the top corner of app  you will see different options there. 
- click on the share icon and try to share the notes with any friend on whattsap you will see that you won't be able to proceed it. 
* Browser: kolab notes
* Operating system:Android 6.0.1

#### Recording Of The Bug

https://youtu.be/2R3oICH4jEo

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@saahir/can-t-share-notes-on-whattsap">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by konradrenner** [comment]
Hi,

thanks for reporting!
But I think it is a problem of WhatsApp, because sharing with different Email Apps or Apps of other messenger apps (e.g. Telegram) works fine.

I will look why WhatsApp is not accepting the message from the Kolab Notes app, but WhatsApp is defintiv reacting different than other apps...

**Comment by Saahir1** [comment]
Yes I checked also it works fine on other apps

On 15-Feb-2018 2:36 PM, "Konrad Renner" <notifications@github.com> wrote:
>
> Hi,
>
> thanks for reporting!
> But I think it is a problem of WhatsApp, because sharing with different
Email Apps or Apps of other messenger apps (e.g. Telegram) works fine.
>
> I will look why WhatsApp is not accepting the message from the Kolab
Notes app, but WhatsApp is defintiv reacting different than other apps...

**Comment by konradrenner** [comment]
I am sorry, but I cannot fix anything. Because I cannot find the problem why WhatsApp is not accepting the share. I have also read the dev notes of whatsapp, how one must create the intent for sharing and kolab notes is doing it this way. Only difference is, that Kolab Notes app also sends the EXTRA_HTMLTEXT field (so that e.g. mail apps get the note text formatted).
