### ISSUE TITLE
New account dialog background incorrect on Android 4.x

### ISSUE THREAD

**Issue by aseigo** [konradrenner/kolabnotes-android#49]
Everything works just beautifully on Android 4.x devices, except the Add Account dialog which has a light grey background. Given the text is white, this makes it hard to use. 

I assume on Android 5.x, your target dev platform, this works better. Feel free to ignore this issue if you do not wish to support Android 4.x fully (though 3/4ths of users are on 4.x still ..)

**Comment by konradrenner** [comment]
On Android 5, this is not a problem. But because I also want to deliver a good experience for Android 4.4 devices, it should be fixed.

Besides this, I don't like this dialog, I think it is ugly (also on Android 5). I think options should be grouped and options which have defaults should be hidden as long as they are not needed to be change (kind of "convention over configuration").

**Comment by konradrenner** [comment]
Will be fixed in 0.1.0-beta5, the reorganisation of the dialog was not done
