### ISSUE TITLE
Refactoring of tag handling

### ISSUE THREAD

**Issue by dugite-code** [konradrenner/kolabnotes-android#53]
Thought I should report this minor issue.

I have a bunch of tags I used to use and then deleted on my Kolab server still showing in the app.

I have uninstalled the app and re-installed since deleting these tags and they still show. I take it this mean they are still on the server and are simply not shown in the web interface

**Comment by konradrenner** [comment]
Thank you for reporting!
At the moment deletion of tags is not supported in the app, also if a tag is deleted on the server, this deletion will not be synced. Because tags are stored global at the moment (they don't belong to an account).

I am not sure how the handling would be the best possible experience:
- store tags global, with the benefit that you don't have to create e.g. the "Work" tag for each account
- store tags per account, with the benefit that deletions or modifications can be synced to and from the server

@dugite-code what should be the preferred way in your opinion?

**Comment by dugite-code** [comment]
I had to stop and think about that a bit, but from a regular Joe user perspective, I think tags per account is probably the most logical. That way each account is it's own logical entity that you can control in a transparent manner, both app side and server side.

This would be especially useful in single account cases like at my work, I know my Boss would only use the app intermittently (if he had it) and the majority of the time access his notes through the web interface. Simple syncing would be the easiest for a user like him to use and understand.

One thing you might consider as an alternative for a possible future improvement is to have suggested tags from linked accounts in the app.

**Comment by konradrenner** [comment]
I think you are right, I will change the tags handling. But I think it is a minor issue, so at the moment I am working on stabilizing the sync in general, so that I can public a public version in Google Play

**Comment by konradrenner** [comment]
I already started with the refactoring of the handling of tags in the app. The work in the sync library (kolabnotes-java) is done and I began to adopt the app.

In the first version of the app with refactored tag handling the following points will be new:
- Tags are not stored central anymore, they are stored per account
- If a tag is deleted/changed for the account on a server, this will be synced
- It will be possible to define colors for tags within the app
- The app will give visual hints on tags with colors

I will not implement the deletion of tags and renaming of tags now because I think this is a dangerous feature. If a tag would be deleted or renamed in the app, this will get synced and so the tag will also be deleted on the server. A Kolab server uses the same tag store not only for notes, but also for e.g. mails. So if the tag is deleted, this not only affects notes, this also affects other PIM objects. So I think this feature should just be available on the server. I don't think the change of a color has an great impact on an workflow, so I will just implement this, for the moment.

**Comment by konradrenner** [comment]
Small status update on this one: I have implemented the changes in the app and sync lib now. But I have to test the whole thing, before I can release it ;-).

There will be some visual changes in the app also (visual hints for colors of tags). @lhitc @dugite-code  there are 2 possibilities for the navigation drawer, what do you think is the better one (the third screenshot shows how it will look in the note overview)?

![overview1](https://cloud.githubusercontent.com/assets/1727807/10379071/d7d290fe-6e0c-11e5-8404-b06bd2b269ed.png)

![overview2](https://cloud.githubusercontent.com/assets/1727807/10379090/eab122c6-6e0c-11e5-9e0f-65884e89e27f.png)

![overview3](https://cloud.githubusercontent.com/assets/1727807/10379091/f0a248cc-6e0c-11e5-9b43-15bcfd1811ff.png)

**Comment by dugite-code** [comment]
I Think having the solid colours would be better (what if someone selects white and the tag text is no longer visible)

Also a slight modification as an option: (rough edit to the screenshot, missed the black outline)
![d7d290fe-6e0c-11e5-8404-b06bd2b269ed](https://cloud.githubusercontent.com/assets/12742064/10383788/f65f824e-6e65-11e5-8397-f0e7740b6295.jpg)

Probably more work than it's worth though ;)

**Comment by konradrenner** [comment]
done with next version
