### ISSUE TITLE
Semi-deleted note NOT_LOADED

### ISSUE THREAD

**Issue by lhitc** [konradrenner/kolabnotes-android#72]
I'm using Kolab Notes on smartphone and tablet. Sync interval on both is the default one from the times when the interval could not be configured (1 day afaik).
On Thursday I created a note on the smartphone that got synced automatically to the server. I deleted it on Friday on the smartphone but it was still present on the server this morning (Saturday). So far no problem.
On the tablet I found a note titled "NOT_LOADED" with no content but the timestamp of the previously mentioned note (color also was wrong). Manually syncing the tablet did not change anything, still "NOT_LOADED".
After manually syncing the smartphone, the note disappeared in IMAP and another manual sync of the tablet made it also disappear from the tablet.
That NOT_LOADED thing leaves the user in a state of inconfidence what's going on.

**Comment by konradrenner** [comment]
I have made changes to the sync logic because of issue #62 . The version with the new sync was published on Friday midnight, so maybe the problem is, that there was some inconsistence because of a note which was "partial" synced between the versions.

Can you reproduce the problem with the new version?

**Comment by lhitc** [comment]
At the moment I can't reproduce the problem, so probably that was temporary due to the new sync.
I suggest closing the issue.
