### ISSUE TITLE
New Notebooks are not synced

### ISSUE THREAD

**Issue by turbomettwurst** [konradrenner/kolabnotes-android#78]
When creating a new Notebook (in Roundcube) after Setting up Kolab-Notes on my Phone the new Notebook is not synchronized to the Client. Notes within pre-existing Notebooks update nicely.
Running on Cyanogen 12.1 Nightly, problem has persisted for several weeks, so I hope CM is not to blame.

**Comment by turbomettwurst** [comment]
Just noticed it doesn't sync the second Notebook at all. I removed Kolab-Notes and reinstalled it (from f-droid), added the Account and still it only syncs the default folder: Notes

**Comment by konradrenner** [comment]
Hi,
per default kolabnotes-android just syncs the Notes Folder of you IMAP account. This is because per account on your Android device, their is exactly 1 root folder (and if you don't specify a folder, kolabnotes-android takes the "Notes" folder).

If you want to sync (or subscribe, like the web ui names it) another top level folder/notebook, you just have to create another account on your Android device (accounts are unique with the E-Mail address and root folder you specify). That means, you can specify many accounts per E-Mail address, with different root folders for the notes.

The reason why I implemented it this way is, that it is possibly to have different sync intervalls and account names for different root folders. Starting with version 1.0.0 you can also specify if you want to sync shared folders per account on your Android device.

E.g. I have 3 different accounts on my Android device, which all sync with my Kolab Now account. But for each account on my Android device, I have specified another root folder and sync intervall.

In the attached screenshot, you can see, where you can specify the root folder (textfield "IMAP Wurzelordner").
![bearbeitet](https://cloud.githubusercontent.com/assets/1727807/11150285/a7a551aa-8a27-11e5-8aaf-c78a97540785.png)

Does this information help you? Are you able to sync your other root folders now?

Yours, Konrad

**Comment by turbomettwurst** [comment]
That does actually make sense, in a weird way :)
It kind of works now, a little wonky..
When i go to "Notes from all accounts" it does show the all notes, but it does not show the second Notebook in the sidebar, there it only shows the Notebook from the "active" Account. That, i guess, is by design?
In addition every refresh/ui reload throws me back into the "Notes from selected account" view.
While i do see your logic, i find it to be confusing as hell :camel: 
Still a big thanx is in order, you finally made the notes feature in kolab useful :)

**Comment by konradrenner** [comment]
Yep, it works like designed :-). The "Notes from all accounts overview" is just there, that you can switch into a note without changing the account before.

Thank you!
