### ISSUE TITLE
Slow Sync due to EXAMINE commands on each folder

### ISSUE THREAD

**Issue by grote** [konradrenner/kolabnotes-android#82]
When syncing the account, Kolab Notes does an EXAMINE IMAP command on each folder. For accounts that have a large number of folders, this can take some time.

**Comment by konradrenner** [comment]
@grote can you please check this apk https://www.dropbox.com/s/llx6vd5hrptt387/app-release.apk?dl=0 if it solves this issue?

Does it maybe also solve issue #81 ?

The problem was that the check if a folder is a notes folder was done after opening the folder. Java Mail sends the EXAMINE command when the open Method is called (so this was done for each folder on your account :-/ ). I have fixed this now, so that the GETANNOTATION command is sent before.

**Comment by grote** [comment]
Thanks for looking into this so quickly! I'm reluctant to run code downloaded from dropbox and hand over my account credentials to it. Couldn't you push the fix? If you don't want it in master yet, you could push it to another branch.

**Comment by konradrenner** [comment]
Fix is pushed and the apk will get published on Google Play and F-Droid. Please let me know if it works for you.

**Comment by grote** [comment]
I tested the new version and can confirm that the sync is faster now and that EXAMINE is not called anymore an all folders. There's probably still room to optimize the IMAP conversation further, but this can be done later.
