### ISSUE TITLE
Sync Interval is not honored

### ISSUE THREAD

**Issue by grote** [konradrenner/kolabnotes-android#84]
I have set up my account with a sync interval of 2 hours and have background sync enabled in Android. However, it is now almost 24h hours and the account was still not synced.

**Comment by konradrenner** [comment]
Have you specified the sync intervall during account creation or have you specified the intervall during an account change?
Are the values correct set when you start the edit account activity (do you see in the "more options" area the values for 2 Hours)?

**Comment by grote** [comment]
I have specified it already during account creation. If I go to change account, I do see the "2 Hours" still. However, at the moment, if I go to settings, accounts, I see the accounts were last synced yesterday and not 2 hours ago.

**Comment by konradrenner** [comment]
I have found it. The sync intervall is calculated wrong in the case "Hour" is selected. So in your case, the account will get synced every 2 days, instead of every 2 hours. I am really sorry for this!

I will fix it soon, after that you have to change your account, so that the sync intervall is updated in the Android sync service.

**Comment by grote** [comment]
Awesome, thank you!

**Comment by konradrenner** [comment]
Should be fixed with 1.1.0
